# Generated by Django 3.1.2 on 2020-10-25 12:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reFree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='workExperience',
            field=models.CharField(choices=[('0', '<1 year'), ('1', '1-2 years'), ('2', '2-5 years'), ('3', '>5years')], default='1', max_length=1),
        ),
    ]
