# Generated by Django 3.1.2 on 2020-10-29 07:20

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('reFree', '0002_auto_20201025_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='DEFAULT VALUE', max_length=128, region=None),
        ),
    ]
