# Generated by Django 3.1.3 on 2020-11-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reFree', '0002_auto_20201122_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallinks',
            name='link',
            field=models.CharField(default='hel', max_length=30),
            preserve_default=False,
        ),
    ]
