# Generated by Django 3.1.2 on 2020-11-15 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reFree', '0002_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='emailsToSend',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follow_time',
        ),
        migrations.AddField(
            model_name='projects',
            name='creation',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_follows_us', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_we_follow', to=settings.AUTH_USER_MODEL),
        ),
    ]
