# Generated by Django 3.1.2 on 2020-10-09 11:18

from django.db import migrations, models
import reFree.models


class Migration(migrations.Migration):

    dependencies = [
        ('reFree', '0002_projects_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Company'},
        ),
        migrations.AlterModelOptions(
            name='component',
            options={'verbose_name_plural': 'Component'},
        ),
        migrations.AlterModelOptions(
            name='finaldesign',
            options={'verbose_name_plural': 'FinalDesign'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='sociallinks',
            options={'verbose_name_plural': 'SocialLinks'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'User'},
        ),
        migrations.AddField(
            model_name='component',
            name='upload',
            field=models.ImageField(default=0, upload_to=reFree.models.user_directory_path),
            preserve_default=False,
        ),
    ]
