# Generated by Django 3.1.2 on 2020-10-29 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reFree', '0003_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='phonenumber',
        ),
    ]
