# Generated by Django 3.1.2 on 2020-10-09 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reFree', '0003_auto_20201009_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emailsToSend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reFree.user'),
        ),
    ]
