# Generated by Django 3.1.2 on 2020-11-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reFree', '0003_auto_20201115_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name_plural': 'Follow'},
        ),
    ]
