# Generated by Django 3.1.2 on 2020-10-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reFree', '0004_user_emailstosend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='emailsToSend',
        ),
    ]
