# Generated by Django 3.1.2 on 2020-11-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reFree', '0004_auto_20201115_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='display',
            field=models.ImageField(blank=True, null=True, upload_to='projectdisplays/'),
        ),
    ]
