# Generated by Django 3.1.2 on 2020-11-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reFree', '0005_auto_20201029_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='finaldesign',
            name='finaldesign',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
