# Generated by Django 3.1.2 on 2020-11-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reFree', '0006_finaldesign_finaldesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AlterField(
            model_name='component',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='components/'),
        ),
    ]
